### PR TITLE
Correct markdown at 09_beancount_query_language.md

### PR DESCRIPTION
**Pull request by AndreyBalandin**
Correct markdown at 09_beancount_query_language.md

### CODE REVIEW

**Comment by xuhcc** [comment]
Hello @AndreyBalandin 
Markdown files in this repo are generated automatically from official Beancount documentation. If we want to fix wrong formatting in this file there are two options:
* Change formatting in the [source document](https://docs.google.com/document/d/1s0GOZMcrKKCLlP29MD7kHO4L88evrwWdIO0p4EwRBE0/edit#heading=h.agpdf4fbvn2). It is likely that there are some invisible artifacts that cause parser to fail. To do so, one needs to request  permission to edit document from the Beancount maintainer. I currently do not have such permission.
* Or we can improve the parser.

**Comment by AndreyBalandin** [comment]
Ok. I understood.

**Comment by xuhcc** [comment]
I got a permission from Martin and changed paragraph styles in google doc. Now it is being parsed correctly: 1b51920008bbff662bfa0af0dc912c85657badbd. Thank you for bringing this to our attention!

**Comment by AndreyBalandin** [comment]
Thank you! Appreciate your responsiveness.

**Comment by xuhcc** [comment]
Fixed that too.

**Pull request closed without merging**
